In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.2'

In [3]:
np.random.seed(42)

arr = np.random.randint(1, 101, size=(10, 10))

print(arr)
print(arr.shape)

[[ 52  93  15  72  61  21  83  87  75  75]
 [ 88 100  24   3  22  53   2  88  30  38]
 [  2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47]
 [ 62  51  55  64   3  51   7  21  73  39]
 [ 18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36]
 [ 50   4   2   6  54   4  54  93  63  18]
 [ 90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24]]
(10, 10)


In [4]:
A = arr[:5, :7]
B = arr[:7, 5:]
C = arr[5:, :7]

print("A:")
print(A)
print("Shape of A:", A.shape)

print("\nB:")
print(B)
print("Shape of B:", B.shape)

print("\nC:")
print(C)
print("Shape of C:", C.shape)

A:
[[ 52  93  15  72  61  21  83]
 [ 88 100  24   3  22  53   2]
 [  2  64  60  21  33  76  58]
 [ 91  59  42  92  60  80  15]
 [ 62  51  55  64   3  51   7]]
Shape of A: (5, 7)

B:
[[21 83 87 75 75]
 [53  2 88 30 38]
 [76 58 22 89 49]
 [80 15 62 62 47]
 [51  7 21 73 39]
 [ 9 90 53  2 84]
 [47 35 78 81 36]]
Shape of B: (7, 5)

C:
[[ 18   4  89  60  14   9  90]
 [ 92  60  71  44   8  47  35]
 [ 50   4   2   6  54   4  54]
 [ 90  44  34  74  62 100  14]
 [ 72  78  87  62  40  85  80]]
Shape of C: (5, 7)


In [5]:
sum_AC = A + C

print("A + C:")
print(sum_AC)

A + C:
[[ 70  97 104 132  75  30 173]
 [180 160  95  47  30 100  37]
 [ 52  68  62  27  87  80 112]
 [181 103  76 166 122 180  29]
 [134 129 142 126  43 136  87]]


In [6]:
multiplication_AB = A @ B

print("A × B:")
print(multiplication_AB)

A × B:
[[20122 11674 26370 23707 18684]
 [10905 13935 20597 13796 17099]
 [14767 13190 17673 15971 16268]
 [20075 19632 26407 23792 25049]
 [14246 14254 18372 15931 16944]]


In [8]:
np.random.seed(100)

arr2 = np.random.randint(1, 101, size=(10, 10))

print(arr2)
print(arr2.shape)

[[ 9 25 68 88 80 49 11 95 53 99]
 [54 67 99 15 35 25 16 61 59 17]
 [10 94 87  3 28  5 32  2 14 84]
 [ 5 92 60 68  8 50 48 66 62 15]
 [56 72 81  3 95 20 99 64 54 28]
 [57 31 49 48 40 39 45 19 65 57]
 [35 54 75 18 73 14 31 18 54 69]
 [51 92 92 84 54 79  1 14 58 77]
 [ 4 71  4 85 80 11 88 61  4 49]
 [53 44 37  6 72 39 87 95 99 43]]
(10, 10)


In [9]:
print("1 x 100:")
print(arr2.reshape(1, 100))

print("2 x 50:")
print(arr2.reshape(2, 50))

print("4 x 25:")
print(arr2.reshape(4, 25))

print("5 x 20:")
print(arr2.reshape(5, 20))

print("10 x 10:")
print(arr2.reshape(10, 10))

print("20 x 5:")
print(arr2.reshape(20, 5))

print("25 x 4:")
print(arr2.reshape(25, 4))

print("50 x 2:")
print(arr2.reshape(50, 2))

print("100 x 1:")
print(arr2.reshape(100, 1))

1 x 100:
[[ 9 25 68 88 80 49 11 95 53 99 54 67 99 15 35 25 16 61 59 17 10 94 87  3
  28  5 32  2 14 84  5 92 60 68  8 50 48 66 62 15 56 72 81  3 95 20 99 64
  54 28 57 31 49 48 40 39 45 19 65 57 35 54 75 18 73 14 31 18 54 69 51 92
  92 84 54 79  1 14 58 77  4 71  4 85 80 11 88 61  4 49 53 44 37  6 72 39
  87 95 99 43]]
2 x 50:
[[ 9 25 68 88 80 49 11 95 53 99 54 67 99 15 35 25 16 61 59 17 10 94 87  3
  28  5 32  2 14 84  5 92 60 68  8 50 48 66 62 15 56 72 81  3 95 20 99 64
  54 28]
 [57 31 49 48 40 39 45 19 65 57 35 54 75 18 73 14 31 18 54 69 51 92 92 84
  54 79  1 14 58 77  4 71  4 85 80 11 88 61  4 49 53 44 37  6 72 39 87 95
  99 43]]
4 x 25:
[[ 9 25 68 88 80 49 11 95 53 99 54 67 99 15 35 25 16 61 59 17 10 94 87  3
  28]
 [ 5 32  2 14 84  5 92 60 68  8 50 48 66 62 15 56 72 81  3 95 20 99 64 54
  28]
 [57 31 49 48 40 39 45 19 65 57 35 54 75 18 73 14 31 18 54 69 51 92 92 84
  54]
 [79  1 14 58 77  4 71  4 85 80 11 88 61  4 49 53 44 37  6 72 39 87 95 99
  43]]
5 x 20:
[[ 9 25 68 88 80 49

In [10]:
print("2 x 5 x 10:")
print(arr2.reshape(2, 5, 10))

print("2 x 10 x 5:")
print(arr2.reshape(2, 10, 5))

print("4 x 5 x 5:")
print(arr2.reshape(4, 5, 5))

print("5 x 2 x 10:")
print(arr2.reshape(5, 2, 10))

print("5 x 4 x 5:")
print(arr2.reshape(5, 4, 5))

print("5 x 5 x 4:")
print(arr2.reshape(5, 5, 4))

print("5 x 10 x 2:")
print(arr2.reshape(5, 10, 2))

print("10 x 2 x 5:")
print(arr2.reshape(10, 2, 5))

print("10 x 5 x 2:")
print(arr2.reshape(10, 5, 2))

2 x 5 x 10:
[[[ 9 25 68 88 80 49 11 95 53 99]
  [54 67 99 15 35 25 16 61 59 17]
  [10 94 87  3 28  5 32  2 14 84]
  [ 5 92 60 68  8 50 48 66 62 15]
  [56 72 81  3 95 20 99 64 54 28]]

 [[57 31 49 48 40 39 45 19 65 57]
  [35 54 75 18 73 14 31 18 54 69]
  [51 92 92 84 54 79  1 14 58 77]
  [ 4 71  4 85 80 11 88 61  4 49]
  [53 44 37  6 72 39 87 95 99 43]]]
2 x 10 x 5:
[[[ 9 25 68 88 80]
  [49 11 95 53 99]
  [54 67 99 15 35]
  [25 16 61 59 17]
  [10 94 87  3 28]
  [ 5 32  2 14 84]
  [ 5 92 60 68  8]
  [50 48 66 62 15]
  [56 72 81  3 95]
  [20 99 64 54 28]]

 [[57 31 49 48 40]
  [39 45 19 65 57]
  [35 54 75 18 73]
  [14 31 18 54 69]
  [51 92 92 84 54]
  [79  1 14 58 77]
  [ 4 71  4 85 80]
  [11 88 61  4 49]
  [53 44 37  6 72]
  [39 87 95 99 43]]]
4 x 5 x 5:
[[[ 9 25 68 88 80]
  [49 11 95 53 99]
  [54 67 99 15 35]
  [25 16 61 59 17]
  [10 94 87  3 28]]

 [[ 5 32  2 14 84]
  [ 5 92 60 68  8]
  [50 48 66 62 15]
  [56 72 81  3 95]
  [20 99 64 54 28]]

 [[57 31 49 48 40]
  [39 45 19 65 57]
  [35